# Setup
title:        Carlos Samaniego
tagline:      App developer, Web developer, mobile developer, you name it
quote:        Let's make stuff
baseurl:      ""
paginate:     1
username:     catu52

# About/contact
author:
  name:       Carlos Samaniego
  url:        http://yourhomepage.com 

# Gems
plugins:
  - jekyll-paginate

#Others
markdown: kramdown
#theme: jekyll-theme-cayman