# Setup
title:        Carlos Samaniego
tagline:      Just a site
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Carlos Samaniego
  url:        http://yourhomepage.com 

# Gems
plugins:
  - jekyll-paginate

#Others
markdown: kramdown